name: Test

on:
  push:

env:
  CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_AUTH_TOKEN }}'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: |
          nix profile install --accept-flake-config github:cachix/cachix
          cachix use cachix-test
      # - uses: cachix/cachix-action@v12
      #   with:
      #     name: cachix-test
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Lint SQL
        run: cachix watch-exec cachix-test -- nix develop -L -v --show-trace --command ./dev-scripts/lint-sql
